apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-pvvt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-pvvt
    app.kubernetes.io/part-of: test-annotations-app-bajf
  name: test-annotations-pvvt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-pvvt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-pvvt
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-demx-tenant/test-annotations-app-bajf/test-annotations-pvvt@sha256:73e09d595ff2f02d0df688dfa4e113ae95fe3ed687b5d9f57f0b9d9dc0bf7bce
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
